import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
	title: "söngLa",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="relative">
				<Header />
				<div className="min-h-[calc(100vh_-_80px)]">{children}</div>
				<Toaster />
				<Footer />
			</body>
		</html>
	);
}
